[world]
name = "ZK Battleship"
description = "Provably fair on-chain Battleship with ZK proofs"
seed = "battleship"

[namespace]
default = "battleship"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x13d9ee239f33fea4f8785b9e3870ade909e20a9599ae7cd62c1c292b73af1b7"
private_key = "0x1c9053c053edf324aec366a34c6901b1095b07af69495bffec7d7fe21effb1b"

[writers]
"battleship" = [
  "battleship-game_management",
  "battleship-coin_flip",
  "battleship-board_commit",
  "battleship-gameplay",
  "battleship-proof_verify",
  "battleship-timeout",
  "battleship-escrow",
]
