[world]
name = "ZK Battleship"
description = "Provably fair on-chain Battleship with ZK proofs"
seed = "battleship"

[namespace]
default = "battleship"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x04b9579af308a28c5c1c54a869af4a448e14a41ca6c4e69caccb0aba3a24be69"

[writers]
"battleship" = [
  "battleship-game_management",
  # Additional systems will be added as they're implemented:
  # "battleship-coin_flip",
  # "battleship-board_commit",
  # "battleship-gameplay",
  # "battleship-proof_verify",
  # "battleship-timeout",
  # "battleship-escrow",
]
