[package]
cairo-version = "2.12.2"
name = "battleship"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.12.2"
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[profile.mainnet]
# Mainnet deployment profile
