# Torii configuration for Sepolia testnet
world_address = "0x4b9579af308a28c5c1c54a869af4a448e14a41ca6c4e69caccb0aba3a24be69"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"
start_block = 0                                                                      # Start from beginning (or set to recent block for faster sync)
database_dir = ".torii_db_sepolia"                                                   # Separate DB for Sepolia
manifest_path = "../apps/client/src/dojo/manifest_sepolia.json"                      # Use Sepolia manifest for schema

[server]
http_port = 8081
# gRPC uses default port 50051
http_cors_origins = ["*"]
