[package]
name = "battleship_board_commit"
type = "bin"
authors = ["BitcoinShip"]
# Note: Requires Noir >= 1.0.0-beta.9 (poseidon2 v0.4.0 dependency)

[dependencies]
# Poseidon2 (Noir) by TaceoLabs. The repo is a multi-crate workspace, so we
# point at the "poseidon2" subdirectory and pin a released tag.
poseidon2 = { git = "https://github.com/TaceoLabs/noir-poseidon", tag = "v0.4.0", directory = "poseidon2" }
